ODDESTODDS/Models/ErrorViewModel.cs
using System;

namespace ODDESTODDS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ODDESTODDS/Controllers/BettingAdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ODDESTODDS.Application.DtoModels.Game;
using ODDESTODDS.Application.Interface.BettingOperation;
using ODDESTODDS.Helpers;

namespace ODDESTODDS.Controllers
{

    public class BettingAdminController : Controller
    {
        private readonly IBettingOperationService _bettingService;
        public BettingAdminController(IBettingOperationService bettingService)
        {
            _bettingService = bettingService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _bettingService.GetCurrentGames(0);
            ViewData["game_list"] = response.Result;
            return View();
        }

      
        public IActionResult AddorEdit(long Id=0)
        {
            if (Id == 0)
                return View(new CreateGameDto());
            else
              
                return View(_bettingService.GetGameForEdit(Id).Result.Result);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AddorEdit([Bind("Id,OddId,HomeTeam,AwayTeam,HomeOdd,AwayOdd,DrawOdd,GameStartTime")] CreateGameDto model)
        {
            if (ModelState.IsValid)
            {
                if(model.Id>0 && model.OddId>0)
                  await _bettingService.UpdateGame(model);
                else
                   await _bettingService.AddGame(model);
                await ChannelHelper.Trigger(model, "betting", "game_event");
                return RedirectToAction(nameof(Index));
            }
            return View(model);




        }

       
        public async Task<IActionResult> Delete(long Id)
        {
            await _bettingService.DeleteGames(Id);
            await ChannelHelper.Trigger(Id, "betting", "game_event");
            return RedirectToAction(nameof(Index));
           
        }
        

    }
}

ODDESTODDS/Controllers/BettingGuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ODDESTODDS.Application.DtoModels.Game;
using ODDESTODDS.Application.Interface.BettingOperation;

namespace ODDESTODDS.Controllers
{

   
    public class BettingGuestController : Controller
    {
        private readonly IBettingOperationService _bettingService;
        public BettingGuestController(IBettingOperationService bettingService)
        {
            _bettingService = bettingService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _bettingService.GetCurrentGames();
            ViewData["game_list"] = response.Result;
            return View();
        }
        [HttpGet]
        //[Route("api/[controller]/GetAll")]
        public async Task<IEnumerable<GamePreviewDto>> GetAll()
        {

            var response = await _bettingService.GetCurrentGames();
            return response.Result;
        }

    }
}

ODDESTODDS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ODDESTODDS.Models;

namespace ODDESTODDS.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ODDESTODDS/Views/BettingAdmin/AddorEdit.cshtml
@model ODDESTODDS.Application.DtoModels.Game.CreateGameDto

@{
    ViewData["Title"] = "Create";
}
@section Header{
    <link href="~/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />

}
<h2>Game Form</h2>


<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddorEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="OddId" />
            <div class="form-group">
                <label asp-for="HomeTeam" class="control-label"></label>
                <input asp-for="HomeTeam" class="form-control" />
                <span asp-validation-for="HomeTeam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwayTeam" class="control-label"></label>
                <input asp-for="AwayTeam" class="form-control" />
                <span asp-validation-for="AwayTeam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeOdd" class="control-label"></label>
                <input asp-for="HomeOdd" type="number" class="form-control" />
                <span asp-validation-for="HomeOdd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrawOdd" class="control-label"></label>
                <input asp-for="DrawOdd" type="number" class="form-control" />
                <span asp-validation-for="DrawOdd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwayOdd" class="control-label"></label>
                <input asp-for="AwayOdd" type="number" class="form-control" />
                <span asp-validation-for="AwayOdd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameStartTime" class="control-label"></label>
                <div class="input-group date form_datetime col-md-12" data-date="2019-06-15 14:45" data-date-format="dd/mm/yyyy hh:mm:ss " data-link-field="dtp_input1">
                    <input asp-for="GameStartTime" size="16" type="datetime" id="GameStartTime" class="form-control" readonly />
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <span asp-validation-for="GameStartTime" class="text-danger"></span>
                <input type="hidden" id="dtp_input1" value="" /><br />
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="Index" class="btn btn-primary btn-block">Back to List</a>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/bootstrap-datetimepicker.min.js"></script>
    @*<script src="~/js/bootstrap-datetimepicker.fr.js"></script>*@
    <script src="~/js/datepicker-init.js"></script>
}

ODDESTODDS/Views/BettingAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<hr />
<div class="row">
    <div class="col-lg-4">
        <a asp-area="" asp-controller="BettingAdmin" asp-action="AddorEdit" class="btn btn-info">Create New Game</a>
    </div>
</div>
    

<table class="table">
    <thead>
        <tr>

            <th>
                Start-Time
            </th>
            <th>
                Games
            </th>
            <th>
                1
            </th>
            <th>
                X
            </th>
            <th>
                2
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var game in (dynamic)ViewData["game_list"])
        {
            <tr>
                <td>

                    @game.GameStartTime
                </td>

                <td>

                    @game.TeamDescription
                </td>

                <td>
                    @game.HomeOdd
                </td>
                <td>
                    @game.DrawOdd

                </td>
                <td>
                    @game.AwayOdd

                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@game.Id" onclick="return confirm('Are you sure you want to delete this record?')"><i class="glyphicon glyphicon-remove"> </i></a>
                    <a asp-action="AddorEdit" asp-route-id="@game.Id"><i class="glyphicon glyphicon-edit"> </i></a>
                </td>


            </tr>

        }

    </tbody>
</table>

ODDESTODDS/Views/BettingGuest/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Games</h2>

<table class="table table-striped table-responsive table-hover" id="tblGames">
    <thead>
        <tr>

            <th>
                Start-Time
            </th>
            <th>
                Games
            </th>
            <th>
                1
            </th>
            <th>
                X
            </th>
            <th>
                2
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
@section Scripts{
    <script src="https://js.pusher.com/4.2/pusher.min.js"></script>
    <script src="https://unpkg.com/moment" ></script>
    <script type="text/javascript">

        $(function () {
            
             LoadData();  
       
         });
         Pusher.logToConsole = true;
        const pusher = new Pusher('8547d7df8ea09890aded', {
            cluster: 'eu',
             forceTLS: true
        });
        const channel = pusher.subscribe('betting');

        channel.bind('game_event', function (data) {
            console.log('ChannelBind: ', data);
            LoadData();
            alert(data.message);
            
        });
        function LoadData() {  
        $("#tblGames tbody tr").remove();  
        $.ajax({  
            type: 'GET',  
            url: '@Url.Action("GetAll")',  
            dataType: 'json',  
            data: { id: '' },  
            success: function (data) {
                console.log('Data From Get ALL:', data);
                var items = '';  
            
                $.each(data, function (i, item) {  
                    var rows = "<tr>"  
                    + "<td>" + moment(item.gameStartTime ).format("dddd, MMMM Do YYYY, h:mm:ss a")+"</td>"  
                    + "<td>" + item.teamDescription + "</td>"  
                    + "<td><span class='table-remove'><button type='button'class='btn btn-info btn-rounded btn-sm my-0'> " + item.homeOdd + "</button></span></td>"
                    + "<td><span class='table-remove'><button type='button'class='btn btn-info btn-rounded btn-sm my-0'> " + item.drawOdd + "</button></span></td>"  
                    + "<td><span class='table-remove'><button type='button'class='btn btn-info btn-rounded btn-sm my-0'> " + item.awayOdd + "</button></span></td>"    
 
                    + "</tr>";  
                    $('#tblGames tbody').append(rows);  
                });  
            },  
            error: function (ex) {  
                console.log("ERROR: ", ex);
                var r = jQuery.parseJSON(response.responseText);  
                alert("Message: " + r.Message);  
                alert("StackTrace: " + r.StackTrace);  
                alert("ExceptionType: " + r.ExceptionType);  
            }  
        });  
        return false;  
    } 
      
    </script>
}

ODDESTODDS/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ODDESTODDS/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ODDESTODDS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ODDESTODDS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ODDESTODDS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Header",false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ODDESTODDS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="BettingGuest" asp-action="Index">Punter</a></li>
                    <li><a asp-area="" asp-controller="BettingAdmin" asp-action="Index">Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ODDESTODDS</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

        
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>